INSERT INTO `alunos` (`codigo`,`nome`,`uf`)
VALUES
  (1,"Aladdin Hooper","Maranhão"),
  (2,"Felix Underwood","Trentino-Alto Adige"),
  (3,"Claire Wong","Northern Mindanao"),
  (4,"Knox Tate","Connacht"),
  (5,"Chloe Stein","Saskatchewan"),
  (6,"Emerson Lowe","Guanacaste"),
  (7,"Ashely Pratt","Veracruz"),
  (8,"Quynn Mccray","Berlin"),
  (9,"Xander Hill","Connacht"),
  (10,"Lavinia Wynn","Arequipa"),
  (11,"Burton Diaz","Antwerpen"),
  (12,"Amery Martin","North West"),
  (13,"Thor Ross","Bauchi"),
  (14,"Elliott Yates","Donetsk oblast"),
  (15,"Audra Moss","Andalucía"),
  (16,"Sophia Mercado","North Island"),
  (17,"Allistair Hicks","Zhōngnán"),
  (18,"Jolie Moore","Västra Götalands län"),
  (19,"Sylvester Lopez","Xīběi"),
  (20,"Ruby Willis","Putumayo"),
  (21,"Perry Peck","Lambayeque"),
  (22,"Ebony Gay","Rajasthan"),
  (23,"Noah Anderson","Rogaland"),
  (24,"Laith Barber","Hậu Giang"),
  (25,"Len Clarke","Mecklenburg-Vorpommern"),
  (26,"Rose Hopper","Mazowieckie"),
  (27,"Jelani Booker","British Columbia"),
  (28,"Reese Green","Lower Austria"),
  (29,"Tyrone Joseph","Mississippi"),
  (30,"Yeo Hayden","Central Region"),
  (31,"Joseph Williams","Oost-Vlaanderen"),
  (32,"Stone Christensen","Vermont"),
  (33,"Arthur Powers","Central Sulawesi"),
  (34,"Regina Hanson","West Region"),
  (35,"Armand Mays","Eastern Cape"),
  (36,"Orson Morrison","Kursk Oblast"),
  (37,"Camilla Morrison","Munster"),
  (38,"Dara Mcfarland","Querétaro"),
  (39,"Sylvia Carney","Risaralda"),
  (40,"Ryan Santiago","San José"),
  (41,"Luke Albert","Lạng Sơn"),
  (42,"Sage Woods","Cusco"),
  (43,"Raja Woods","Nordrhein-Westphalen"),
  (44,"Anthony Ingram","Calabarzon"),
  (45,"John Rowland","Central Java"),
  (46,"Dane Key","Mykolaiv oblast"),
  (47,"Tarik Palmer","Drenthe"),
  (48,"Isadora Allison","Extremadura"),
  (49,"Abbot Mcfadden","Bremen"),
  (50,"Megan Flynn","West-Vlaanderen");
INSERT INTO `alunos` (`codigo`,`nome`,`uf`)
VALUES
  (51,"Ashely Ray","North-East Region"),
  (52,"Imani Ashley","Caraga"),
  (53,"Cassandra Snyder","Nordland"),
  (54,"Deirdre Osborn","Nord-Pas-de-Calais"),
  (55,"Halla Gonzales","Nova Scotia"),
  (56,"Perry Roth","Gauteng"),
  (57,"Duncan Morgan","Tver Oblast"),
  (58,"Aladdin Pearson","Östergötlands län"),
  (59,"Murphy Parker","Central Region"),
  (60,"Delilah Ayers","Gilgit Baltistan"),
  (61,"Cassady Santos","Gia Lai"),
  (62,"Marah Foley","Thái Nguyên"),
  (63,"Blythe Nguyen","Emilia-Romagna"),
  (64,"Philip Hodge","Sląskie"),
  (65,"Hu Stephens","Saarland"),
  (66,"Henry Mccarty","Roxburghshire"),
  (67,"Cooper Marquez","Guanacaste"),
  (68,"Andrew Farrell","Northern Territory"),
  (69,"Chancellor Donovan","Limburg"),
  (70,"Rigel Ortega","Kano"),
  (71,"Silas Mclaughlin","Luik"),
  (72,"Joseph Bennett","Chocó"),
  (73,"Willow Hewitt","Aisén"),
  (74,"Barclay Rivera","West Nusa Tenggara"),
  (75,"Gage Myers","East Region"),
  (76,"Natalie Bailey","Pará"),
  (77,"Jameson Christian","Limousin"),
  (78,"Regan King","Ceuta"),
  (79,"Rhoda Reeves","Renfrewshire"),
  (80,"Zenia Alford","North Chungcheong"),
  (81,"Helen Prince","Nova Scotia"),
  (82,"Unity Melendez","Troms og Finnmark"),
  (83,"Timothy Mccullough","Cordillera Administrative Region"),
  (84,"Derek Bentley","FATA"),
  (85,"Lael Owen","West Sulawesi"),
  (86,"Talon Bentley","West Region"),
  (87,"Jane Martinez","Chiapas"),
  (88,"Colin Valentine","National Capital Region"),
  (89,"Hunter Joyce","Ogun"),
  (90,"Tad Avila","Davao Region"),
  (91,"Lacy Murray","Lazio"),
  (92,"Holly Daniels","Tabasco"),
  (93,"MacKenzie Bell","Utrecht"),
  (94,"Raymond Mercado","Picardie"),
  (95,"Patrick Tran","Ulyanovsk Oblast"),
  (96,"Fletcher Todd","Huáběi"),
  (97,"Heather Pacheco","Champagne-Ardenne"),
  (98,"Dillon Horn","Guaviare"),
  (99,"Sawyer Decker","Utrecht"),
  (100,"Dennis Pitts","Piemonte");
